package model;
// Generated 28/04/2015 01:11:11 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Empleado generated by hbm2java
 */
public class Empleado  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String ape1;
     private String ape2;
     private char sexo;
     private String estCivil;
     private String tipoSangre;
     private Date fechaNac;
     private Boolean enfermedad;
     private String espEnferme;
     private String nacionalidad;
     private String direccion;
     private Integer telCasa;
     private Integer telCel;
     private String emergencia;
     private Integer telEmergencia;
     private String puesto;
     private Date fechaIngreso;
     private Date fechaEgreso;
     private byte[] foto;

    public Empleado() {
    }

	
    public Empleado(int id, String nombre, String ape1, String ape2, char sexo, String estCivil, String tipoSangre, Date fechaNac, String nacionalidad, Date fechaIngreso, Date fechaEgreso) {
        this.id = id;
        this.nombre = nombre;
        this.ape1 = ape1;
        this.ape2 = ape2;
        this.sexo = sexo;
        this.estCivil = estCivil;
        this.tipoSangre = tipoSangre;
        this.fechaNac = fechaNac;
        this.nacionalidad = nacionalidad;
        this.fechaIngreso = fechaIngreso;
        this.fechaEgreso = fechaEgreso;
    }
    public Empleado(int id, String nombre, String ape1, String ape2, char sexo, String estCivil, String tipoSangre, Date fechaNac, Boolean enfermedad, String espEnferme, String nacionalidad, String direccion, Integer telCasa, Integer telCel, String emergencia, Integer telEmergencia, String puesto, Date fechaIngreso, Date fechaEgreso, byte[] foto) {
       this.id = id;
       this.nombre = nombre;
       this.ape1 = ape1;
       this.ape2 = ape2;
       this.sexo = sexo;
       this.estCivil = estCivil;
       this.tipoSangre = tipoSangre;
       this.fechaNac = fechaNac;
       this.enfermedad = enfermedad;
       this.espEnferme = espEnferme;
       this.nacionalidad = nacionalidad;
       this.direccion = direccion;
       this.telCasa = telCasa;
       this.telCel = telCel;
       this.emergencia = emergencia;
       this.telEmergencia = telEmergencia;
       this.puesto = puesto;
       this.fechaIngreso = fechaIngreso;
       this.fechaEgreso = fechaEgreso;
       this.foto = foto;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApe1() {
        return this.ape1;
    }
    
    public void setApe1(String ape1) {
        this.ape1 = ape1;
    }
    public String getApe2() {
        return this.ape2;
    }
    
    public void setApe2(String ape2) {
        this.ape2 = ape2;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public String getEstCivil() {
        return this.estCivil;
    }
    
    public void setEstCivil(String estCivil) {
        this.estCivil = estCivil;
    }
    public String getTipoSangre() {
        return this.tipoSangre;
    }
    
    public void setTipoSangre(String tipoSangre) {
        this.tipoSangre = tipoSangre;
    }
    public Date getFechaNac() {
        return this.fechaNac;
    }
    
    public void setFechaNac(Date fechaNac) {
        this.fechaNac = fechaNac;
    }
    public Boolean getEnfermedad() {
        return this.enfermedad;
    }
    
    public void setEnfermedad(Boolean enfermedad) {
        this.enfermedad = enfermedad;
    }
    public String getEspEnferme() {
        return this.espEnferme;
    }
    
    public void setEspEnferme(String espEnferme) {
        this.espEnferme = espEnferme;
    }
    public String getNacionalidad() {
        return this.nacionalidad;
    }
    
    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelCasa() {
        return this.telCasa;
    }
    
    public void setTelCasa(Integer telCasa) {
        this.telCasa = telCasa;
    }
    public Integer getTelCel() {
        return this.telCel;
    }
    
    public void setTelCel(Integer telCel) {
        this.telCel = telCel;
    }
    public String getEmergencia() {
        return this.emergencia;
    }
    
    public void setEmergencia(String emergencia) {
        this.emergencia = emergencia;
    }
    public Integer getTelEmergencia() {
        return this.telEmergencia;
    }
    
    public void setTelEmergencia(Integer telEmergencia) {
        this.telEmergencia = telEmergencia;
    }
    public String getPuesto() {
        return this.puesto;
    }
    
    public void setPuesto(String puesto) {
        this.puesto = puesto;
    }
    public Date getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(Date fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public Date getFechaEgreso() {
        return this.fechaEgreso;
    }
    
    public void setFechaEgreso(Date fechaEgreso) {
        this.fechaEgreso = fechaEgreso;
    }
    public byte[] getFoto() {
        return this.foto;
    }
    
    public void setFoto(byte[] foto) {
        this.foto = foto;
    }




}


